---
kind: pipeline
name: Lint
steps:
- commands:
  - golangci-lint run
  image: golangci/golangci-lint:v1.50.1
  name: lint
trigger:
  ref:
  - refs/heads/main
  - refs/pull/**
  - refs/tags/**
type: docker
---
kind: pipeline
name: Test
steps:
- commands:
  - go test -cover -v ./...
  image: golang:1.18
  name: test
trigger:
  ref:
  - refs/heads/main
  - refs/pull/**
  - refs/tags/**
type: docker
---
kind: signature
hmac: 83402b74ee3b8edcd02df7d3a1d1b2dcd51a2f480aca0072cfa76a7242feab32

...
